version: '3.6'
services:
  kyc-react-juridico:
    build: .
    container_name: kyc-react-juridico
    tty: true
    stdin_open: true
    restart: always
    command: yarn start
    environment:
      PORT: 3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    networks:
      network:

volumes:
  node_modules:
networks:
  network:
    driver: bridge