export default {
    GLOBAL_CONFIG_REQUEST: 'GLOBAL_CONFIG_REQUEST',
    GLOBAL_CONFIG_SUCCESS: 'GLOBAL_CONFIG_SUCCESS',
    GLOBAL_CONFIG_ERROR: 'GLOBAL_CONFIG_ERROR',

    LOGIN_GET_ATRRIBUTES_REQUEST: 'GET_LOGIN_ATRRIBUTES_REQUEST',
    LOGIN_GET_ATRRIBUTES_SUCCESS: 'GET_LOGIN_ATRRIBUTES_SUCCESS',
    LOGIN_GET_ATRRIBUTES_ERROR: 'GET_LOGIN_ATRRIBUTES_ERROR',

    LOGIN_GET_ADDITIONAL_ATTRIBUTES_REQUEST: 'GET_ADDITIONAL_ATTRIBUTES_REQUEST',
    LOGIN_GET_ADDITIONAL_ATRRIBUTES_SUCCESS: 'GET_ADDITIONAL_ATRRIBUTES_SUCCESS',
    LOGIN_GET_ADDITIONAL_ATRRIBUTES_ERROR: 'GET_ADDITIONAL_ATRRIBUTES_ERROR',

    LOGIN_POST_REQUEST: 'POST_LOGIN_REQUEST',
    LOGIN_POST_SUCCESS: 'POST_LOGIN_SUCCESS',
    LOGIN_POST_ERROR: 'POST_LOGIN_ERROR',

    LOGIN_ADDITIONAL_POST_REQUEST: 'POST_ADDITIONAL_LOGIN_REQUEST',
    LOGIN_ADDITIONAL_POST_SUCCESS: 'POST_ADDITIONAL_LOGIN_SUCCESS',
    LOGIN_ADDITIONAL_POST_ERROR: 'POST_ADDITIONAL_LOGIN_ERROR',

    OTP_GET_ATRRIBUTES_REQUEST: 'OTP_GET_ATRRIBUTES_REQUEST',
    OTP_GET_ATRRIBUTES_SUCCESS: 'OTP_GET_ATRRIBUTES_SUCCESS',
    OTP_GET_ATRRIBUTES_ERROR: 'OTP_GET_ATRRIBUTES_ERROR',
    OTP_POST_REQUEST: 'OTP_POST_REQUEST',
    OTP_POST_SUCCESS: 'OTP_POST_SUCCESS',
    OTP_POST_ERROR: 'OTP_POST_ERROR',

    SET_LOGIN_CRED: 'SET_LOGIN_CRED',
    FLUSH_LOGIN_CRED: 'FLUSH_LOGIN_CRED',

    GET_FORM_REQUEST: 'GET_FORM_REQUEST',
    GET_FORM_SUCCESS: 'GET_FORM_SUCCESS',
    GET_FORM_ERROR: 'GET_FORM_ERROR',
    POST_FORM_REQUEST: 'POST_FORM_REQUEST',
    POST_FORM_SUCCESS: 'POST_FORM_SUCCESS',
    POST_FORM_ERROR: 'POST_FORM_ERROR',
    AUTO_POST_FORM_REQUEST: 'AUTO_POST_FORM_REQUEST',
    AUTO_POST_FORM_SUCCESS: 'AUTO_POST_FORM_SUCCESS',
    AUTO_POST_FORM_ERROR: 'AUTO_POST_FORM_ERROR',

    UPDATE_FORM_FIELD_VALUE: 'UPDATE_FORM_FIELD_VALUE',
    UPDATE_ADDITIONAL_FORM_FIELD_VALUE: 'UPDATE_ADDITIONAL_FORM_FIELD_VALUE',
    ADDITIONAL_FORM_POST_SUCCESS: 'ADDITIONAL_FORM_POST_SUCCESS',

    GET_SIGNERS_SUCCESS: 'GET_SIGNERS_SUCCESS',
    GET_SINGLE_SIGNER_SUCCESS: 'GET_SINGLE_SIGNER_SUCCESS',
    DELETE_SIGNER_SUCCESS: 'DELETE_SIGNER_SUCCESS',

    GET_PARTNER_SUCCESS: 'GET_PARTNER_SUCCESS',
    DELETE_PARTNER_SUCCESS: 'DELETE_PARTNER_SUCCESS',


    CLONE_SIGNER_BLOCK: 'CLONE_SIGNER_BLOCK',
    REMOVE_SIGNER_BLOCK: 'REMOVE_SIGNER_BLOCK',

    CLONE_REPRESENTATIVE_BLOCK: 'CLONE_REPRESENTATIVE_BLOCK',
    REMOVE_REPRESENTATIVE_BLOCK: 'REMOVE_REPRESENTATIVE_BLOCK',

    UPDATE_REPRESENTATIVE_FORM_FIELD_VALUE: 'UPDATE_REPRESENTATIVE_FORM_FIELD_VALUE',
    REMOVE_IMAGE_PREVIEW: 'REMOVE_IMAGE_PREVIEW',

    CLONE_CURRENCY: 'CLONE_CURRENCY',
    REMOVE_CLONE_CURRENCY: 'REMOVE_CLONE_CURRENCY'
}
