export default {
  ROOT: "/",
  LOG_IN: '/login',
  COMPANY: '/company',
  OTP: '/login/otp',
  ERROR: '/error',
  ABOUT: "/about-us",
  FORM1: "/form/step1",
  FORM2: "/form/step2",
  FORM3: "/form/step3",
  FORM4: "/form/step4",
  FORM5: "/form/step5",
  FORM6: "/form/step6",
  FORM7: "/form/step7",
  FORM8: "/form/step8",
  DONE: "/form/done",
  DECISION: "/form/decision",
  ENTRYLIST: "/entries",
  PARTNERS: "/partners",
  A_FORM1: "/additional/form/step1",
  A_FORM2: "/additional/form/step2",
  A_FORM3: "/additional/form/step3",
  A_FORM4: "/additional/form/step4",
  A_FORM5: "/additional/form/step5",
  A_FORM6: "/additional/form/step6",
  A_SUBMIT: "/additional/form/submit",
  SIGNERS: "/additional/signers",
};
